name: Update Blog Posts # 워크플로 이름 (Actions 탭에서 표시됨)

# 워크플로 실행 조건 정의
on:
  # 1. main 브랜치에 푸시될 때 실행
  push:  
    branches:
      - main

  # 2. 스케줄에 따라 정기적으로 실행 (cron 형식)
  schedule:
    - cron: '0 0 * * *'    # 매일 9:00 KST 실행
    - cron: '0 15 * * *'   # 매일 자정 KST 실행

  workflow_dispatch:  # 수동 실행을 위한 트리거 추가

# 실제 작업 정의
jobs:
  update_blog:
    runs-on: ubuntu-latest  # Ubuntu 최신 버전의 가상 머신에서 실행

    steps:
        # 저장소 코드 체크아웃 (소스코드 다운로드)
      - name: Checkout
        uses: actions/checkout@v3

        # 파이썬 환경 설치
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

        # 필용한 파이썬 패키지 설치
      - name: Install dependencies
        run: |
          pip install gitpython requests
        # gitpython: Git 작업을 Python 코드에서 다룰 경우 (현재 스크립트에선 사용 안할수도)

    # 경로 문제 디버깅용: 실제 workspace 디렉토리 구조 출력
      - name: Show files in workspace (for debug)
        run: ls -R
        working-directory: ${{ github.workspace }}

        # Velog RSS를 읽어 .md 파일로 저장하는 사용자 정의 스크립트 실행
        # 문제: 이전 실행에서 'scripts/update_blog.py' 파일을 찾지 못해 오류 발생
        # 해결 방법: 'working-directory'를 ${{ github.workspace }}로 명시하여 정확한 루트 경로 설정
        # 또한 실제 해당 경로에 'scripts/update_blog.py' 파일이 존재해야
      - name: Run script
        run: python ./scripts/update_blog.py
        working-directory: ${{ github.workspace }}

        # 액션에서 변경 파일을 커밋하려 했지만 git add A를 써버려 실제 존재하지 않는 파일 이름을 추가하려다 실패 
        # 원래 의도 : 모든 변경사항을 스테이징해 커밋 후 main 브랜치에 푸시하는 기능
        # 문제 원인 : 잘못된 명령 때문에 항상 에러가 발생해 업데이트가 진행되지 않았다.
      - name: Commit and push if changed
        run: |
          git config --global user.name 'Sondanha'
          git config --global user.email '155447715+Sondanha@users.noreply.github.com'
          git checkout -B main 
          git add -A
          git diff --cached --quiet || git commit -m "Update blog posts"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/Sondanha/velog.git
          git pull --rebase origin main || true
          git push origin main
