name: Update Blog Posts # 워크플로 이름 (Actions 탭에서 표시됨)

# 워크플로 실행 조건 정의
on:
  # 1. main 브랜치에 푸시될 때 실행
  push:  
    branches:
      - main

  # 2. 스케줄에 따라 정기적으로 실행 (cron 형식)
  schedule:
    - cron: '0 0 * * *'    # 매일 9:00 KST 실행
    - cron: '0 15 * * *'   # 매일 자정 KST 실행

# 실제 작업 정의
jobs:
  update_blog:
    runs-on: ubuntu-latest  # Ubuntu 최신 버전의 가상 머신에서 실행

    steps:
        # 저장소 코드 체크아웃 (소스코드 다운로드)
      - name: Checkout
        uses: actions/checkout@v3

        # 파이썬 환경 설치
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

        # 필용한 파이썬 패키지 설치
      - name: Install dependencies
        run: |
          pip install feedparser gitpython
        # feedparser: RSS 피드 파싱용
        # gitpython: Git 작업을 Python 코드에서 다룰 경우 (현재 스크립트에선 사용 안할수도)


        # Velog RSS를 읽어 .md 파일로 저장하는 사용자 정의 스크립트 실행
      - name: Run script
        run: python ./scripts/update_blog.py

        # 변경된 파일이 있다면 커밋하고 main 브랜치로 푸시
      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/Sondanha/velog.git    
          git add .
          git diff --cached --quiet || git commit -m "Update blog posts"
          git push origin main
      # x-access-token: 사용자 정보 명시
